### ISSUE TITLE
Not possible to set password from mobile

### ISSUE THREAD

**Issue by Gjessing1** [Lio5n/peekaboo#1]
I am using the newest Obsidian version on android with the plugin innstalled. After submitting a password and clicking the next menu item about what to hide i get the prompt that i must set a password first.

I have given it multiple attempts and restarted the app without any change in behaviour.

**Comment by Lio5n** [comment]
Thank you for your feedback. I have fixed this bug in the latest version. You're welcome to try it out, and if there are any more issues, please let me know promptly. @Gjessing1

**Comment by Gjessing1** [comment]
It is working now, thank you very much!
